"use strict"

export const images = {
  Ackbar: "img/Ackbar.jpg",
  "Adi Gallia": "img/Adi Gallia.jpg",
  "Anakin Skywalker": "img/Anakin Skywalker.jpg",
  "Arvel Crynyd": "img/Arvel Crynyd.jpg",
  "Ayla Secura": "img/Ayla Secura.jpg",
  "Bail Prestor Organa": "img/Bail Prestor Organa.jpg",
  "Barriss Offee": "img/Barriss Offee.jpg",
  "Ben Quadinaros": "img/Ben Quadinaros.jpg",
  "Beru Whitesun lars": "img/Beru Whitesun lars.jpg",
  "Bib Fortuna": "img/Bib Fortuna.jpg",
  "Biggs Darklighter": "img/Biggs Darklighter.jpg",
  "Boba Fett": "img/Boba Fett.jpg",
  Bossk: "img/Bossk.jpg",
  "C-3PO": "img/C-3PO.jpg",
  Chewbacca: "img/Chewbacca.jpg",
  "Cliegg Lars": "img/Cliegg Lars.jpg",
  Cordé: "img/Cordé.jpg",
  "Darth Maul": "img/Darth Maul.jpg",
  "Darth Vader": "img/Darth Vader.jpg",
  "Dexter Jettster": "img/Dexter Jettster.jpg",
  Dooku: "img/Dooku.jpg",
  Dormé: "img/Dormé.jpg",
  "Dud Bolt": "img/Dud Bolt.jpg",
  "Eeth Koth": "img/Eeth Koth.jpg",
  "Finis Valorum": "img/Finis Valorum.jpg",
  Gasgano: "img/Gasgano.jpg",
  Greedo: "img/Greedo.jpg",
  "Gregar Typho": "img/Gregar Typho.jpg",
  Grievous: "img/Grievous.jpg",
  "Han Solo": "img/Han Solo.jpg",
  "IG-88": "img/IG-88.jpg",
  "Jabba Desilijic Tiure": "img/Jabba Desilijic Tiure.jpg",
  "Jango Fett": "img/Jango Fett.jpg",
  "Jar Jar Binks": "img/Jar Jar Binks.jpg",
  "Jek Tono Porkins": "img/Jek Tono Porkins.jpg",
  "Jocasta Nu": "img/Jocasta Nu.jpg",
  "Ki-Adi-Mundi": "img/Ki-Adi-Mundi.jpg",
  "Kit Fisto": "img/Kit Fisto.jpg",
  "Lama Su": "img/Lama Su.jpg",
  "Lando Calrissian": "img/Lando Calrissian.jpg",
  "Leia Organa": "img/Leia Organa.jpg",
  Lobot: "img/Lobot.jpg",
  "Luke Skywalker": "img/Luke Skywalker.jpg",
  "Luminara Unduli": "img/Luminara Unduli.jpg",
  "Mace Windu": "img/Mace Windu.jpg",
  "Mas Amedda": "img/Mas Amedda.jpg",
  "Mon Mothma": "img/Mon Mothma.jpg",
  "Nien Nunb": "img/Nien Nunb.jpg",
  "Nute Gunray": "img/Nute Gunray.jpg",
  "Obi-Wan Kenobi": "img/Obi-Wan Kenobi.jpg",
  "Owen Lars": "img/Owen Lars.jpg",
  "Padmé Amidala": "img/Padmé Amidala.jpg",
  Palpatine: "img/Palpatine.jpg",
  "Plo Koon": "img/Plo Koon.jpg",
  "Poggle the Lesser": "img/Poggle the Lesser.jpg",
  "Quarsh Panaka": "img/Quarsh Panaka.jpg",
  "Qui-Gon Jinn": "img/Qui-Gon Jinn.jpg",
  "R2-D2": "img/R2-D2.jpg",
  "R4-P17": "img/R4-P17.jpg",
  "R5-D4": "img/R5-D4.jpg",
  "Ratts Tyerel": "img/Ratts Tyerel.jpg",
  "Raymus Antilles": "img/Raymus Antilles.jpg",
  "Ric Olié": "img/Ric Olié.jpg",
  "Roos Tarpals": "img/Roos Tarpals.jpg",
  "Rugor Nass": "img/Rugor Nass.jpg",
  "Saesee Tiin": "img/Saesse Tiin.jpg",
  "San Hill": "img/San Hill.jpg",
  "Shaak Ti": "img/Shaak Ti.jpg",
  Sebulba: "img/Sebulba.jpg",
  "Shmi Skywalker": "img/Shmi Skywalker.jpg",
  "Sly Moore": "img/Sly Moore.jpg",
  Tarfful: "img/Tarfful.jpg",
  "Taun We": "img/Taun We.jpg",
  "Tion Medon": "img/Tion Medon.jpg",
  "Wat Tambor": "img/Wat Tambor.jpg",
  Watto: "img/Watto.jpg",
  "Wedge Antilles": "img/Wedge Antilles.jpg",
  "Wicket Systri Warrick": "img/Wicket Systri Warrick.jpg",
  "Wilhuff Tarkin": "img/Wilhuff Tarkin.jpg",
  "Yarael Poof": "img/Yarael Poof.jpg",
  Yoda: "img/Yoda.jpg",
  "Zam Wesell": "img/Zam Wesell.jpg",
}
